### ISSUE TITLE
openfoam needs rebuild

### ISSUE THREAD

**Issue by adrianinsaval** [arch4edu/arch4edu#182]
trying to run a simpleFoam case I get errors like

> /opt/OpenFOAM/OpenFOAM-v2206/platforms/linux64GccDPInt32Opt/bin/renumberMesh: error while loading shared libraries: libboost_system.so.1.79.0: cannot open shared object file: No such file or directory

due to updated boost version, there is `/lib/libboost_system.so.1.80.0` in my system, not sure if scotch and parmetis also require a rebuild but it wouldn't hurt I guess. Is there no way of auto detecting when these things need a rebuild?

**Comment by petronny** [comment]
Thanks for the report. They can be automatically rebuilt when boost updates. But we have to manually set the boost upstream for the first time.

**Comment by adrianinsaval** [comment]
thanks! is there a way of figuring out which dependencies would require a rebuild when updated?

**Comment by petronny** [comment]
Well for now python and boost are the mostly reported dependencies that always require rebuilds. In most time, we can just check if python or boost is mentioned in the PKGBUILD. So scotch and parmetis should be fine since boost in not in their PKGBUILDs.

But there are packages that implictly depends on python or boost. And any package which contains dynamic link libraries (*.so) may cause this issue. Currently we (and even the official repository) still don't have a proper way to solve this issue. Please report to us if any package needs rebuild.

**Comment by petronny** [comment]
https://github.com/arch4edu/arch4edu/commit/e97bbbe51f21f7058c3881d298211f04ede39578
