### ISSUE TITLE
why is 'yay' included on the repo?

### ISSUE THREAD

**Issue by csxr** [arch4edu/arch4edu#26]
I wonder why an AUR helper is included, according to the [wiki](https://wiki.archlinux.org/index.php/AUR_helpers):

> - Warning: AUR helpers are not supported by Arch Linux.
> - Since AUR helpers are unsupported, they are not present in the official repositories.

I know that this is not an official (yet) repository but this is almost a similar case.

**Comment by petronny** [comment]
Actually we don't really __support__ almost all of the packages in arch4edu.
We just give the binaries to save everyone's time.
We only deal with the bugs about packaging and the other bugs should be reported to AUR.
Also we don't have package testing since it is just [planned](https://github.com/archlinuxcn/repo/issues/976).

Since we don't need to support a package if we want to add it to arch4edu,
I think for now we can add any package if redistributable.

**Comment by petronny** [comment]
Actually all the AUR helpers are added since we announced the ARM support.

They will be helpful for developers to obtain PKGBUILD for packages only officially supported by Archlinux but not ArchlinuxARM.

**Comment by csxr** [comment]
> We just give the latest binaries to save everyone's time.


- This is a good point to an univeristy/PhD student. 

Personally I was struggling with some packages on past semesters. I have in mind some packages I would like to add but to do it right I'll do a research to make sure it fits for arch4edu.

> We only deal with the bugs about packaging and the other bugs should be reported to AUR.

I think we should put some side-note in README or somewhere that specifies this just to avoid misconceptions.

Becuase there's `google-chrome` AUR package and the reason it's not on the official repos according to a Google license (following a [reddit post](https://www.reddit.com/r/archlinux/comments/alg954/why_is_google_chrome_in_the_aur/) with this on mind):
> Google has a blanket clause in place that disallow modification if you intend to distribute, which ABS would have to violate as it needs to extract the .deb or .rpm and convert it to pacman's format, on top of moving it to /opt. So rather than ask permission, arch elected to just ship chromium (which has a much more lenient license and also allows arch to use abs to directly build it form source) and just say if you want chrome you can use the aur. :)


And for some other packages it would be something similar.

> Since we don't need to support a package if we want to add it to arch4edu,
I think for now we can add any package if redistributable.

> Actually all the AUR helpers are added since we announced the ARM support.

+1 on this.
This is the first time I know the existence of software like @calilbot and all the software related that can give a hand to make the updates more easily.


The reason I decided to open this non-issue it's because I know that in a near future this kind of question will be asked so we're saving time to handle the thread, and personally I was curious, nothing more than that.
Thanks!

**Comment by petronny** [comment]
Oops, `google-chrome` are removed from the repo now. It will take a few hours to be removed from the site.

> Personally I was struggling with some packages on past semesters. I have in mind some packages I would like to add but to do it right I'll do a research to make sure it fits for arch4edu.

Just FIY, we won't add `matlab`, `mathematica` although they won't work without your own license.
I'm working on a way to put `intel-compiler-base` and so on to a private repository that only the build machine can access to build packages depend on them. `intel-mkl` is fine since is redistributable .

About the private repository, the `arch4edu-x86_64-build` on build machine is not as same as the one in the public `devtools-arch4edu`. It will use the private repository to build packages. It used to have `cudnn` and `nccl` when they are not redistributable and can only be downloaded from `developer.nvidia.com` with your account. Now it's empty since `cudnn` and `nccl` are provided by `[community]`.

**Comment by csxr** [comment]
> Just FIY, we won't add matlab, mathematica although they won't work without your own license.

Got it. 

I'll take a look to the packages I've choose to maintain, any other advice?
Thanks in advance.

**Comment by petronny** [comment]
You can try to run `lilac.py` locally by following [`How to run lilac.py`](https://github.com/arch4edu/arch4edu/wiki/Let-calil-update-packages-automatically#how-to-run-lilacpy) in the wiki.
Here is also some explanations for the variables but I'm still working on them.

More advanced usage of `lilac.py` will be listed in [`Tricks and tips`](https://github.com/arch4edu/arch4edu/wiki/Tricks-and-tips) but I will do it later.

If you have questions about `lilac.py` we can discuss them in the [maintainer's page](https://github.com/orgs/arch4edu/teams/maintainers) and I will add the answers to wiki.
