### ISSUE TITLE
[Out of date] hip-hcc

### ISSUE THREAD

**Issue by acxz** [arch4edu/arch4edu#76]
Just making an out of date issue on `hip-hcc`.
Package is on 3.3.0-6 on the [AUR](https://aur.archlinux.org/packages/hip-hcc) but is still on 3.3.0-5 [here](https://github.com/arch4edu/arch4edu/tree/master/hip-hcc).

As a side note, how often do packages get autoupdated by calibot?

**Comment by petronny** [comment]
calilbot runs once per day. And it will try to update all packages which have new version.

It does try to update `hip-hcc` in every runs since `3.3.0-6` is pushed to AUR.
However, a package blocked the build system due to a bug of `devtools`.

I pushed a patch (4c429d4df017abafbc1e50dd0a930358382adcc3) to bypass the bug a few hours ago. 
Let's see if it can be updated this run.

**Comment by petronny** [comment]
5092208eda660b070a045c2c6b93e6a0de75cc4f
